### ISSUE TITLE
BMI for PCRGLowb (MVP)

### ISSUE THREAD

**Issue by yifatdzigan** [eWaterCycle/ewatercycle-forecast#12]

**Comment by yifatdzigan** [comment]
Already done? (https://github.com/eWaterCycle/PCR-GLOBWB_model)

Added for completeness.

**Comment by goord** [comment]
Yes this BMI exists and has been extended by me. However, we may not find the interface flexible enough (e.g. it is only possible to set soil moisture now), but this information has to be gathered when we develop the high-level interface for the demos...
