### ISSUE TITLE
Define parameters for demo

### ISSUE THREAD

**Issue by yifatdzigan** [eWaterCycle/ewatercycle-forecast#5]
The parameters that we would use for the demo (extracted from the forcing) - precipitation, temp.
We would use the following datasets: GFS, GEFS

**Comment by bpmweel** [comment]
Please also comment this to issue #4

**Comment by yifatdzigan** [comment]
Forcing will require precipitation, temp. 

For GFS/GEFS these parameters are:       
* Variable "Total_precipitation_surface_3_Hour_Accumulation"   
*  Variable "Temperature_surface"      

Please download and store the global forecast for 3 months (no specific coordinates).

Note also for Issue #4
